# Generated by Django 5.1.3 on 2024-11-14 17:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcode',
            name='id',
            field=models.CharField(default=accounts.models.generate_custom_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
